# Generated by Django 5.2.5 on 2025-08-28 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to='users.role'),
        ),
        migrations.AlterUniqueTogether(
            name='projectrole',
            unique_together={('project', 'role')},
        ),
    ]
