# Generated by Django 5.2.5 on 2025-08-28 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project'),
        ),
        migrations.AddField(
            model_name='documentfieldvalue',
            name='custom_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='projects.customfield'),
        ),
        migrations.AddField(
            model_name='documentfieldvalue',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.document'),
        ),
        migrations.AlterUniqueTogether(
            name='documentfieldvalue',
            unique_together={('document', 'custom_field')},
        ),
        migrations.AlterUniqueTogether(
            name='documentpage',
            unique_together={('document', 'page_number')},
        ),
    ]
